/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#274e3c",
        "inverse-on-surface": "#f0f1ec",
        "tertiary-fixed-dim": "#dec2a2",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#42311a",
        "surface-bright": "#f9faf5",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4ef",
        "inverse-primary": "#a5d0b8",
        "on-background": "#1a1c19",
        "secondary-fixed": "#a4f5b6",
        "on-surface": "#1a1c19",
        "primary-container": "#123b2a",
        "text-charcoal": "#17211B",
        "surface-container": "#edeee9",
        "on-tertiary-container": "#b2987a",
        "on-tertiary-fixed-variant": "#57432b",
        tertiary: "#2b1c07",
        "surface-dim": "#d9dad6",
        "fresh-leaf": "#65A95C",
        "surface-container-highest": "#e2e3de",
        secondary: "#1b6c3b",
        "secondary-container": "#a4f5b6",
        "secondary-fixed-dim": "#89d89c",
        "outline-variant": "#c1c8c2",
        error: "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7ca68f",
        "on-surface-variant": "#414844",
        "surface-container-high": "#e7e9e4",
        "surface-variant": "#e2e3de",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a5d0b8",
        background: "#f9faf5",
        "on-tertiary-fixed": "#271905",
        surface: "#f9faf5",
        "on-secondary-fixed-variant": "#005228",
        "on-primary": "#ffffff",
        "primary-fixed": "#c0edd4",
        primary: "#002517",
        "on-secondary-fixed": "#00210c",
        "surface-tint": "#3f6653",
        "tertiary-fixed": "#fbdebc",
        "critical-red": "#D93025",
        "sage-bg": "#DDEBDD",
        "on-primary-fixed": "#002114",
        "on-error": "#ffffff",
        outline: "#717973",
        "on-secondary-container": "#237240",
        "error-container": "#ffdad6",
        "risk-amber": "#FFB800",
        "inverse-surface": "#2e312e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        "container-max": "1280px",
        "section-gap": "120px",
        gutter: "32px",
        "margin-desktop": "64px",
        base: "8px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"],
        "data-viz": ["Inter", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "display-lg-mobile": ["44px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-viz": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "32px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
